import { type NextPage } from "next";
import Head from "next/head";
import { RogueApp } from "~/components/RogueApp";
import { Navbar } from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rogue T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <Navbar />
        <RogueApp />
      </main>
    </>
  );
};

export default Home;
